from __future__ import annotations

from pathlib import Path


REPORT_FILES = [
    ("Final report", "reports/final_report.md"),
    ("Draft report", "reports/project_report.md"),
    ("Results summary", "reports/results_summary.md"),
    ("Reproducibility checklist", "reports/reproducibility_checklist.md"),
    ("Final deliverable checklist", "reports/final_deliverable_checklist.md"),
]

CORE_RESULT_FILES = [
    ("Dataset", "data/facts.csv"),
    ("Probe sweep CSV", "figures/probe_sweep.csv"),
    ("Probe sweep figure", "figures/probe_sweep_summary.png"),
    ("Focused capital probe CSV", "figures/probe_capital_answer.csv"),
    ("Focused capital probe figure", "figures/probe_capital_answer.png"),
    ("Activation PCA CSV", "figures/pca_capital_layer8.csv"),
    ("Activation PCA figure", "figures/pca_capital_layer8.png"),
    ("Error analysis CSV", "figures/error_analysis_capital_layer8.csv"),
    ("Error examples CSV", "figures/error_analysis_capital_layer8_errors.csv"),
    ("Activation patching CSV", "figures/activation_patching_capital_recall.csv"),
    ("Activation patching figure", "figures/activation_patching_capital_recall.png"),
    ("Steering CSV", "figures/steering_capital_probe_layer8.csv"),
    ("Steering logit figure", "figures/steering_capital_probe_layer8.png"),
    ("Steering accuracy figure", "figures/steering_capital_probe_layer8_accuracy.png"),
    ("Steering probe accuracy figure", "figures/steering_capital_probe_layer8_probe_accuracy.png"),
    ("Ablation CSV", "figures/ablation_capital_probe_layer8.csv"),
    ("Ablation figure", "figures/ablation_capital_probe_layer8.png"),
    ("Ablation score gap figure", "figures/ablation_capital_probe_layer8_score_gap.png"),
]

SCRIPT_FILES = [
    ("Dataset builder", "scripts/build_dataset.py"),
    ("Environment check", "scripts/check_env.py"),
    ("Probe", "scripts/run_probe.py"),
    ("Probe sweep", "scripts/run_probe_sweep.py"),
    ("Activation PCA", "scripts/run_activation_pca.py"),
    ("Error analysis", "scripts/run_error_analysis.py"),
    ("Activation patching", "scripts/run_activation_patching.py"),
    ("Steering", "scripts/run_steering.py"),
    ("Ablation", "scripts/run_ablation.py"),
    ("Plotting", "scripts/plot_results.py"),
    ("Results summary", "scripts/summarize_results.py"),
    ("Project validation", "scripts/validate_project.py"),
    ("Submission manifest", "scripts/prepare_submission.py"),
]


def status(path_text: str) -> str:
    path = Path(path_text)
    if not path.exists():
        return "MISSING"
    if path.is_file() and path.stat().st_size == 0:
        return "EMPTY"
    return "OK"


def table(rows: list[tuple[str, str]]) -> str:
    lines = [
        "| Item | Path | Status |",
        "|---|---|---|",
    ]
    for name, path in rows:
        lines.append(f"| {name} | `{path}` | {status(path)} |")
    return "\n".join(lines)


def main() -> None:
    lines = [
        "# Submission Manifest",
        "",
        "This file is generated by `python -m scripts.prepare_submission`.",
        "It lists the files that should be included or checked before final course submission.",
        "",
        "## Required Commands Before Submission",
        "",
        "```powershell",
        "python -m scripts.summarize_results --figures-dir figures --out reports/results_summary.md",
        "python -m scripts.validate_project",
        "```",
        "",
        "## Reports",
        "",
        table(REPORT_FILES),
        "",
        "## Core Results",
        "",
        table(CORE_RESULT_FILES),
        "",
        "## Code Entry Points",
        "",
        table(SCRIPT_FILES),
        "",
        "## Recommended Submission Focus",
        "",
        "- Main report: `reports/final_report.md`",
        "- Full codebase: `src/`, `scripts/`, `data/`, `figures/`, `reports/`",
        "- Reproducibility proof: `reports/reproducibility_checklist.md` and `reports/results_summary.md`",
        "",
    ]

    out_path = Path("reports/submission_manifest.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved submission manifest to {out_path}")


if __name__ == "__main__":
    main()
